((nil . ((fill-column . 80)))
   (c++-mode . ((c-file-style . "xivo")
                (project-init . xivo-client-qt-init)))
   (c-mode . ((mode . c++)
              (c-file-style . "xivo")
              (project-init . xivo-client-qt-init))))
